create type public.user_role as enum ('user', 'admin');
create type public.trade_direction as enum ('long', 'short');

create table public.users (
  id integer generated by default as identity primary key,
  "openId" varchar(64) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table public.trades (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  symbol varchar(20) not null,
  direction public.trade_direction not null,
  "entryPrice" varchar(32) not null,
  "exitPrice" varchar(32) not null,
  quantity varchar(32) not null,
  fees varchar(32) not null default '0',
  pnl varchar(32) not null,
  "tradeDate" timestamptz not null,
  "exitDate" timestamptz,
  notes text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.journal (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  "journalDate" timestamptz not null,
  content text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index trades_user_date_idx on public.trades ("userId", "tradeDate");
create index journal_user_date_idx on public.journal ("userId", "journalDate");

alter table public.users enable row level security;
alter table public.trades enable row level security;
alter table public.journal enable row level security;
